"""Added default_image_id, discount and on_sale to Product table

Revision ID: 02e4548ac30e
Revises: cb4cef38cc2b
Create Date: 2019-11-04 10:14:17.366883

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '02e4548ac30e'
down_revision = 'cb4cef38cc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('default_image_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('on_sale', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'product', 'product_image', ['default_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'on_sale')
    op.drop_column('product', 'discount')
    op.drop_column('product', 'default_image_id')
    # ### end Alembic commands ###
