"""deleted thumb column from product_image

Revision ID: 743a12adbc4a
Revises: 02e4548ac30e
Create Date: 2019-11-07 15:28:36.305007

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '743a12adbc4a'
down_revision = '02e4548ac30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_image', 'thumb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image', sa.Column('thumb', mysql.VARCHAR(length=500), nullable=False))
    # ### end Alembic commands ###
