"""Added name to Store Address model

Revision ID: 82df20a186ef
Revises: dbdc74926faf
Create Date: 2020-04-19 14:13:49.983123

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '82df20a186ef'
down_revision = 'dbdc74926faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_address', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_address', 'name')
    # ### end Alembic commands ###
