"""added delete casade foreign keys

Revision ID: c0401ab3f0e4
Revises: 76ef7c78ee7f
Create Date: 2020-02-18 16:40:06.184355

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c0401ab3f0e4'
down_revision = '76ef7c78ee7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_ibfk_1', 'address', type_='foreignkey')
    op.drop_constraint('address_ibfk_2', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'address', 'country', ['country_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('admin_ibfk_2', 'admin', type_='foreignkey')
    op.create_foreign_key(None, 'admin', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cart_item_ibfk_1', 'cart_item', type_='foreignkey')
    op.create_foreign_key(None, 'cart_item', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('client_ibfk_1', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('client_favourite_ibfk_2', 'client_favourite', type_='foreignkey')
    op.drop_constraint('client_favourite_ibfk_1', 'client_favourite', type_='foreignkey')
    op.create_foreign_key(None, 'client_favourite', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_favourite', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('filter_value_ibfk_1', 'filter_value', type_='foreignkey')
    op.create_foreign_key(None, 'filter_value', 'filter', ['filter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_ibfk_3', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_2', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_1', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.drop_constraint('product_ibfk_2', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'creator', ['creator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_image_ibfk_1', 'product_image', type_='foreignkey')
    op.create_foreign_key(None, 'product_image', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_review_ibfk_1', 'product_review', type_='foreignkey')
    op.drop_constraint('product_review_ibfk_2', 'product_review', type_='foreignkey')
    op.create_foreign_key(None, 'product_review', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_review', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_view_ibfk_3', 'product_view', type_='foreignkey')
    op.drop_constraint('product_view_ibfk_1', 'product_view', type_='foreignkey')
    op.create_foreign_key(None, 'product_view', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_view', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_view', type_='foreignkey')
    op.drop_constraint(None, 'product_view', type_='foreignkey')
    op.create_foreign_key('product_view_ibfk_1', 'product_view', 'client', ['client_id'], ['id'])
    op.create_foreign_key('product_view_ibfk_3', 'product_view', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_review', type_='foreignkey')
    op.drop_constraint(None, 'product_review', type_='foreignkey')
    op.create_foreign_key('product_review_ibfk_2', 'product_review', 'product', ['product_id'], ['id'])
    op.create_foreign_key('product_review_ibfk_1', 'product_review', 'client', ['client_id'], ['id'])
    op.drop_constraint(None, 'product_image', type_='foreignkey')
    op.create_foreign_key('product_image_ibfk_1', 'product_image', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_2', 'product', 'creator', ['creator_id'], ['id'])
    op.create_foreign_key('product_ibfk_1', 'product', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_ibfk_1', 'order', 'address', ['address_id'], ['id'])
    op.create_foreign_key('order_ibfk_2', 'order', 'cart', ['cart_id'], ['id'])
    op.create_foreign_key('order_ibfk_3', 'order', 'client', ['client_id'], ['id'])
    op.drop_constraint(None, 'filter_value', type_='foreignkey')
    op.create_foreign_key('filter_value_ibfk_1', 'filter_value', 'filter', ['filter_id'], ['id'])
    op.drop_constraint(None, 'client_favourite', type_='foreignkey')
    op.drop_constraint(None, 'client_favourite', type_='foreignkey')
    op.create_foreign_key('client_favourite_ibfk_1', 'client_favourite', 'client', ['client_id'], ['id'])
    op.create_foreign_key('client_favourite_ibfk_2', 'client_favourite', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_ibfk_1', 'client', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_ibfk_1', 'category', 'category', ['parent_id'], ['id'])
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.create_foreign_key('cart_item_ibfk_1', 'cart_item', 'cart', ['cart_id'], ['id'])
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_foreign_key('admin_ibfk_2', 'admin', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('address_ibfk_2', 'address', 'country', ['country_id'], ['id'])
    op.create_foreign_key('address_ibfk_1', 'address', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
