"""default image to null on delete

Revision ID: e46758f4374f
Revises: 743a12adbc4a
Create Date: 2019-11-08 15:24:57.310948

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e46758f4374f'
down_revision = '743a12adbc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_ibfk_3', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'product_image', ['default_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_3', 'product', 'product_image', ['default_image_id'], ['id'])
    # ### end Alembic commands ###
